### ISSUE TITLE
Debian Version?

### ISSUE THREAD

**Issue by jiriteach** [RamonGiovane/guiptables#1]
Hi - You don't happen to have a version that can be installed with Cockpit running on Debian do you? Thanks

**Comment by RamonGiovane** [comment]
Hi! Unfortunately, we haven't tested.

The way it is, it may work, but with certain limitations. (The iptables installation, for instance, uses the 'yum', CentOS package manager, internally, but the installation is only triggered if the 'iptables' package is missing.)

But you could check the alternative installation mode (without an installation package), which is simpler, actually: 
Go to your Cockpit directory (usually `/usr/share/cockpit`) and perform a `git clone` of this repo. Open the UI, see if it works.

**Comment by jiriteach** [comment]
Thanks. Managed to install using alien. Install alien first in Debian then use alien to install the package. Alien is a installer that can read CentOS packages.

Reloaded Cockpit and it’s appeared up and is showing the correct iptables. It does require me to log in via root however. Is this expected? Thanks

**Comment by RamonGiovane** [comment]
Nice! I'm glad to know that worked. Thanks!
Yes, it does require root, as Iptables naturally needs it to access network interfaces, communicate with kernel and so on...
So, it is needed the same way it would on the CLI.

**Comment by RamonGiovane** [comment]
> Thanks. Managed to install using alien. Install alien first in Debian then use alien to install the package. Alien is a installer that can read CentOS packages.
> 
> Reloaded Cockpit and it’s appeared up and is showing the correct iptables. It does require me to log in via root however. Is this expected? Thanks

Hi, sorry for the late reply.
I just noticed that there's a fork that uses `sudo ` thus allowing non-root members to use it: https://github.com/Niroda/guiptables
I didn't tested it but I know that Cockpit prompts authentication for `sudo `commands, so it might work...
Maybe we can implement the same here.
