### ISSUE TITLE
Make iptables page available in "Administrative access" mode instead of root

### ISSUE THREAD

**Issue by D0m0** [RamonGiovane/guiptables#10]
My version of Cockpit (287-1) has this "Administrative access" mode. Can I use it instead of logging in as root? Or maybe add /usr/sbin/iptables to sudoers file with some fancy protective rules?

**Comment by SeeJayEmm** [comment]
I'd like to second this request. [Root login to cockpit is explicitly disallowed in Debian](https://github.com/cockpit-project/cockpit/issues/18427) (out of the box) and I would prefer not to disable that.

**Comment by RamonGiovane** [comment]
Hi guys, thanks for the feedback. Unfortunately I have been pretty busy lately. But I'm considering about implementing the feature, it doesn't look too complicated.

**Comment by RamonGiovane** [comment]
The feature is available on the latest release https://github.com/RamonGiovane/guiptables/releases/tag/1.4.0
Closing this issue. Let me know if you have any problems.
