### ISSUE TITLE
Erroneous iptables not installed message

### ISSUE THREAD

**Issue by jjspierx** [RamonGiovane/guiptables#17]
I am running a non-RHEL distro and have installed guiptables for my cockpit instance.  When I select Iptables UI option from cockpit menu I get a modal window saying iptables is not installed.  However, this is incorrect.  I have iptables installed, running and enabled on startup.  Any ideas what could be causing this?

**Comment by RamonGiovane** [comment]
I've seen this bug a few times, it usually disappears when refreshing the page, but it's not normal behavior and needs further investigation

**Comment by VarionDrakon** [comment]
I will also add this screenshot to the information:
![image](https://github.com/user-attachments/assets/c493dd69-ded0-410e-838c-f4d5c112be3f)

OS installed: Fedora Server 40

**Comment by jjspierx** [comment]
I think the red bar error message is a clue as to what is going on (I have the same thing).  I think the issue is related to the plugin not having permissions to access files that it needs.

**Comment by RamonGiovane** [comment]
Yes, it seems so.

Which version of Cockpit are you using? I'll try to reproduce the bug here.

**Comment by jjspierx** [comment]
329-1
My guess is it has less to do with the version, and more to do with difference in file permissions on my Linux distro.  I can change file access permissions manually if you can point me in the direction of files that your plugin needs to access.

**Comment by VarionDrakon** [comment]
i use `cockpit` version 327.

**Comment by RamonGiovane** [comment]
I checked the code and this message is triggered when trying to list the system's active network interfaces using the command `sudo ls /sys/class/net `  which is run via the Cockpit API.

Can you run this command on your machines?
If so, the problem may be that Cockpit does not have enough permission to execute commands with sudo. We'll have to check their documentation to solve this.

**Comment by jjspierx** [comment]
> I checked the code and this message is triggered when trying to list the system's active network interfaces using the command `sudo ls /sys/class/net ` which is run via the Cockpit API.
> 
> Can you run this command on your machines? If so, the problem may be that Cockpit does not have enough permission to execute commands with sudo. We'll have to check their documentation to solve this.

I tried the command and it works, but it asks for password obviously before it lists.

**Comment by VarionDrakon** [comment]
> using the command sudo ls /sys/class/net  which is run via the Cockpit API.

I executed the command and here is the result:

![image](https://github.com/user-attachments/assets/ebd66c96-39e3-4c95-8f47-0d1ef691ed86)

**Comment by RamonGiovane** [comment]
I think I found the solution. I changed the way the code calls commands that need sudo.

**Can you guys test the fix Pull Request that I just made please?** You can follow these steps:

1. First, back up your guiptables:
 ```
 mv /usr/share/cockpi/guiptables /usr/share/cockpit/guiptables-backup
 ```
 
2. Then clone the repository (you need to have GitHub CLI installed, follow the official [instructions](https://github.com/cli/cli/blob/trunk/docs/install_linux.md) for this):
 ```
  gh repo clone RamonGiovane/guiptables
 ```
 
3. Then switch to the PR branch. 
 ```
 gh pr checkout 18
 ```
 
4. Then copy the cloned repository to the Cockpit directory:
 ```
 sudo cp -r guiptables/ /usr/share/cockpit/
 ```

Finally, try accessing the Iptables UI and see if the error persists.

**Comment by VarionDrakon** [comment]
Yes. Its work :)
![image](https://github.com/user-attachments/assets/ee432764-16c8-47b0-8aff-146059ef5aeb)

**Comment by RamonGiovane** [comment]
Cool. Thanks for the feedback. I will merge the PR and create a new release.

UPDATE:
Bug fixed on the latest version https://github.com/RamonGiovane/guiptables/releases/tag/1.4.1

Please let me know if you guys still have any problems.

**Comment by jjspierx** [comment]
Sorry for slow response, but I just upgraded and it now works for me!  Thanks so much.
