### ISSUE TITLE
instruções para instalar em sistemas debian

### ISSUE THREAD

**Issue by N4v41** [RamonGiovane/guiptables#2]
projeto bem legal ! tem como fornecer instruções para utilização em sistemas baseados em debian ? 
não conseguir ver a fundo o prjeto mas ele é baseado no starter kit do proprio cockpit ?

**Comment by N4v41** [comment]
consegui realizar a copia dos arquivos para a pasta e parece ter funcionado

**Comment by RamonGiovane** [comment]
Olá! Nós não chegamos a testar no Debian como também solicitado no  issue #1 (o rapaz disse que conseguiu usando Alien). Mas é possível que funcione.
Valeu pelo apoio! :smile:
