### ISSUE TITLE
Icons not showing up properly

### ISSUE THREAD

**Issue by CrazyKidJack** [RamonGiovane/guiptables#4]
### Problem:
All of the icons in the gui just show up as blank boxes:
![image](https://github.com/RamonGiovane/guiptables/assets/43480837/205bb9b8-ec8e-4554-9766-ae6e95e97dd6)
![image](https://github.com/RamonGiovane/guiptables/assets/43480837/51821a3e-674b-4b24-abad-fc51c6f1ca96)

---

### Background info
I used `alien` to convert the `rmp` to a `deb` package and installed with `apt-get`.

Here's some information about my system:
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Here is what I have installed from `cockpit`:
```
# apt list --installed | grep cockpit
cockpit-bridge/stable-backports,now 311-1~bpo12+1 amd64 [installed]
cockpit-system/stable-backports,now 311-1~bpo12+1 all [installed]
cockpit-ws/stable-backports,now 311-1~bpo12+1 amd64 [installed]
```

Here is what I have installed for this cockpit add-on
```
# apt list --installed | grep guip
guiptables/now 1-3 all [installed,local]
```

**Comment by CrazyKidJack** [comment]
Inspecting further, it looks as if the font-awesome.min.css file is not being served properly:
![image](https://github.com/RamonGiovane/guiptables/assets/43480837/09b16693-b522-4100-8bcb-46dd47d9c5c5)

**Comment by RamonGiovane** [comment]
> Inspecting further, it looks as if the font-awesome.min.css file is not being served properly: ![image](https://private-user-images.githubusercontent.com/43480837/317556748-09b16693-b522-4100-8bcb-46dd47d9c5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MjUwOTgsIm5iZiI6MTcxMjUyNDc5OCwicGF0aCI6Ii80MzQ4MDgzNy8zMTc1NTY3NDgtMDliMTY2OTMtYjUyMi00MTAwLThiY2ItNDZkZDQ3ZDljNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDIxMTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOGYyZGU1MjY1ZjFjNTkxYjIyN2U3ZjIxYmY3MTg1YWQ3ZDg0NTEyNGJmNDM2MWU4MDNhOTI4ZTIwNjdkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qNP_U9KdqSBHwpCpzCvkWctEhDbNzLzLVxsO9Kag_0Y)

I got this error in the Chrome's console on Linux Mint, but for some reason the icons were still working.
Testing on RHEL 9, using Firefox I could reproduce the bug. 
Anyways, the fix is merged now :smiley: 
Thanks!
